# -*- mode: k8s -*-
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.appName }}-manager-binding
subjects:
- kind: ServiceAccount
  name: {{ .Values.appName }}-manager
  namespace: {{ .Values.namespace }}  # Replace with your desired namespace
roleRef:
  kind: ClusterRole
  name: {{ .Values.appName }}-manager-role
  apiGroup: rbac.authorization.k8s.io
